export default {
  records: [],
  initialRecords: [],
  intervals: [],
  disciplines: [],
  isFetching: false,
  isFetched: false,
  error: null,
  selectedTime: null,
  selectedDiscipline: null,
  rev: null,
  modalVisibility: false,
  isSaving: false,
  isSaved: false,
  saveErr: null,
};
